name: Docker Image CI

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # or whichever version you're using for your Angular project

      - name: Install Angular CLI
        run: npm install -g @angular/cli@17.3.0

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: ng test --browsers=ChromeHeadless --watch=false

      - name: Build Angular project
        run: ng build --configuration production

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag  clearcb/imin-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push  clearcb/imin-app:latest
